import type { Metadata } from "next";
import { Poppins, Preahvihear } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--poppins",
});

const preahvihear = Preahvihear({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--preahvihear",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${preahvihear.variable}`}>
      <body className="font-preahvihear">{children}</body>
    </html>
  );
}
